//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.19 at 08:28:50 PM EST 
//


package edu.monash.merc.eddy.modc.ws.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.monash.merc.eddy.modc.ws.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.monash.merc.eddy.modc.ws.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WPublishResponse }
     * 
     */
    public WPublishResponse createWPublishResponse() {
        return new WPublishResponse();
    }

    /**
     * Create an instance of {@link WPublishRequest }
     * 
     */
    public WPublishRequest createWPublishRequest() {
        return new WPublishRequest();
    }

    /**
     * Create an instance of {@link WCollection }
     * 
     */
    public WCollection createWCollection() {
        return new WCollection();
    }

    /**
     * Create an instance of {@link WSpatialCoverage }
     * 
     */
    public WSpatialCoverage createWSpatialCoverage() {
        return new WSpatialCoverage();
    }

    /**
     * Create an instance of {@link WSubject }
     * 
     */
    public WSubject createWSubject() {
        return new WSubject();
    }

    /**
     * Create an instance of {@link WParty }
     * 
     */
    public WParty createWParty() {
        return new WParty();
    }

    /**
     * Create an instance of {@link WElectronicAddress }
     * 
     */
    public WElectronicAddress createWElectronicAddress() {
        return new WElectronicAddress();
    }

    /**
     * Create an instance of {@link WIdentifier }
     * 
     */
    public WIdentifier createWIdentifier() {
        return new WIdentifier();
    }

    /**
     * Create an instance of {@link WCitation }
     * 
     */
    public WCitation createWCitation() {
        return new WCitation();
    }

    /**
     * Create an instance of {@link WPublication }
     * 
     */
    public WPublication createWPublication() {
        return new WPublication();
    }

    /**
     * Create an instance of {@link WPerson }
     * 
     */
    public WPerson createWPerson() {
        return new WPerson();
    }

    /**
     * Create an instance of {@link WGroup }
     * 
     */
    public WGroup createWGroup() {
        return new WGroup();
    }

}
